<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>my_control_node</name>
  <version>0.0.1</version>
  <description>A ROS 2 node that subscribes to control commands and modifies them.</description>
  <maintainer email="tsubaki@g.ecc.u-tokyo.ac.jp">mtsubaki</maintainer>
  <license>MIT</license>

  <!-- 必要に応じてテスト依存関係を保持 -->
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>tier4_control_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
